name: Build Preview

on: [pull_request]

jobs:
  build:
    name: 'build PR preview'
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: ljharb/actions/node/install@7f214d8efdbdcefc96ad9689663ef387a195deec
        name: 'nvm install lts/* && npm ci --no-audit'
        env:
          NPM_CONFIG_AUDIT: false
        with:
          node-version: lts/*
          use-npm-ci: true
      - run: npm run build-only
      - run: node scripts/insert_snapshot_warning
      - run: echo ${{ github.event.number }} > out/pr.txt
      - uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/
