name: 'esmeta typecheck'

on: [pull_request]

jobs:
  esmeta-typecheck:
    name: 'esmeta typecheck'
    runs-on: ubuntu-22.04

    env:
      ESMETA_HOME: vendor/esmeta

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: download esmeta
        run: |
          mkdir -p "${ESMETA_HOME}"
          cd "${ESMETA_HOME}"
          git init
          git remote add origin https://github.com/es-meta/esmeta.git
          git fetch --depth 1 origin 154cd346cfad4bfb485de1c34fc9715748e2d517 ;# v0.6.4
          git checkout FETCH_HEAD
      - name: build esmeta
        run: |
          cd "${ESMETA_HOME}"
          sbt assembly
      - name: link
        run: |
          rmdir "${ESMETA_HOME}"/ecma262 \
            && ln -s "$(pwd)" "${ESMETA_HOME}"/ecma262
      - name: typecheck
        run: '"${ESMETA_HOME}"/bin/esmeta tycheck -status -extract:log -tycheck:log -tycheck:ignore=esmeta-ignore.json'
      - name: create logs archive
        run: 'tar --verbose --verbose --create --gzip --file esmeta-logs.tar.gz --directory="${ESMETA_HOME}" logs/'
      - name: upload logs archive
        uses: actions/upload-artifact@v4
        with:
          name: esmeta-logs
          path: esmeta-logs.tar.gz
