name: 'ecma-262'

on:
  pull_request_target:
    branches:
       - '*'
  push:
    branches:
       - main

jobs:
  build:
    name: 'check IPR form'
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: ljharb/actions/node/install@7f214d8efdbdcefc96ad9689663ef387a195deec
        name: 'nvm install lts/* && npm ci --no-audit'
        env:
          NPM_CONFIG_AUDIT: false
        with:
          node-version: lts/*
          use-npm-ci: true
      - run: npm run ipr-check ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || 'HEAD' }}
        env:
          GH_TOKEN: ${{ secrets.GH_IPR_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
